# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='decs',
            new_name='desc',
        ),
    ]
